server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://192.168.2.227:3306/test?characterEncoding=utf8&useSSL=true&autoReconnect=true
    username: test
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
