server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://pc-bp1l50pa694z242v1-pre.mysql.polardb.rds.aliyuncs.com:3306/apolloconfigdb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: liyang
    password: F97kGr7txShz2dbP
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
